#!/usr/bin/env python3
"""tools/gen_example_config.py — regenerate shellai.example.json.

The example config is documentation that the user copies, so drift is not
cosmetic: it once shipped `autopilot_system_prompt`, which *replaces* the tuned
agent prompt, and anyone following the README got a crippled agent. It has
since drifted again (a deleted key lingered, three new ones were missing).

So it is generated, and `evals/test_product_shell.py` fails if the checked-in
file does not match what this produces.

Usage:
    python tools/gen_example_config.py           # rewrite the file
    python tools/gen_example_config.py --check   # exit 1 if it is stale
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

TARGET = ROOT / "shellai.example.json"

COMMENT = (
    "Generated by tools/gen_example_config.py — do not hand-edit. Every key "
    "is OPTIONAL: config is deep-merged over the built-in defaults, so delete "
    "anything you do not want to override. Prompt-override keys are "
    "deliberately excluded — setting autopilot_system_prompt replaces the "
    "tuned agent prompt entirely and measurably degrades the agent."
)


def is_prompt_override(key: str) -> bool:
    return key == "system_prompt" or key.endswith("_system_prompt")


def build() -> dict[str, object]:
    from hexcli.agent import DEFAULT_CONFIG

    out: dict[str, object] = {"_comment": COMMENT}
    for key, value in DEFAULT_CONFIG.items():
        if is_prompt_override(key):
            continue
        out[key] = value
    return out


def render() -> str:
    return json.dumps(build(), indent=2) + "\n"


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != text:
            print("shellai.example.json is stale — run tools/gen_example_config.py")
            return 1
        print("shellai.example.json is up to date")
        return 0
    TARGET.write_text(text, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(build()) - 1} keys)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
